server:
  port: '8082'

spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/product_db}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:password}