server:
  port: '8082'

spring:
  datasource:
    url: ${PRODUCTS_DATASOURCE_URL:jdbc:postgresql://localhost:5432/products_db}
    username: ${PRODUCTS_DATASOURCE_USERNAME:postgres}
    password: ${PRODUCTS_DATASOURCE_PASSWORD:password}

    flyway:
      enabled: true
      baseline-on-migrate: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
