server:
  port: '8081'

spring:
  datasource:
    url: ${RECIPES_DATASOURCE_URL:jdbc:postgresql://localhost:5432/recipes_db}
    username: ${RECIPES_DATASOURCE_USERNAME:postgres}
    password: ${RECIPES_DATASOURCE_PASSWORD:password}

    flyway:
      enabled: true
      baseline-on-migrate: true

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
