server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///home/evhen/Documents/GitHub/meal-app/config-service/src/main/resources/config