name: Build and deploy

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-deploy:
    name: Build and Deploy Config Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: maven
      - name: Unit tests
        run: mvn -B test --file pom.xml

      - name: Build
        run: |
          mvn clean
          mvn -B package --file pom.xml



